### ISSUE TITLE
KMKE

### ISSUE THREAD

**Issue by jhill001** [GiacomoLaw/IF-Charts#14]

**Comment by GiacomoLaw** [comment]
Hi there! Thanks for requesting. Is this currently in IF? 🛩

**Comment by GiacomoLaw** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [KMKE](https://trello.com/c/EPcdfEjI/7-kmke)

**Comment by jhill001** [comment]
Yes it is in the Chicago region

**Comment by GiacomoLaw** [comment]
@jhill001 Sorry, just realised!

**Comment by GiacomoLaw** [comment]
Adding now!

**Comment by GiacomoLaw** [comment]
Added! 😄

**Comment by jhill001** [comment]
Thank You!!

**Comment by GiacomoLaw** [comment]
No problem, hope you enjoy using IF-Charts!
