### ISSUE TITLE
EGLL

### ISSUE THREAD

**Issue by Adam167** [GiacomoLaw/IF-Charts#6]
I'd love the charts for this

**Comment by GiacomoLaw** [comment]
EGLL is likely to be added :)

**Comment by GiacomoLaw** [comment]
Adding EGLL now.

**Comment by GiacomoLaw** [comment]
Added!

https://github.com/GiacomoLaw/IF-Charts/commit/d2fc588f2a805b3124bc37674fa9341cf4c98088
